### ISSUE TITLE
Feature - Check url aip

### ISSUE THREAD

**Issue by PalmTreeVI** [jinglescode/nostr-url-shortener#11]
Similiar to get api but instead checks the short url an replies with the long url.

https://w3.do/check?url=<url>

For example `https://w3.do/check?url=https://w3.do/xNQ8b0HZ` would return  
```
{
  "id":"xNQ8b0HZ",
  "url":"https://github.com/jinglescode/nostr-url-shortener"
}
```

**Comment by jinglescode** [comment]
Check using ID

```
GET https://w3.do/check?id=<id>
```

For example: [https://w3.do/check?id=MSbbaU8l](https://w3.do/check?id=MSbbaU8l)
