### ISSUE TITLE
Make URL box longer for very long URLs so I can see the whole string

### ISSUE THREAD

**Issue by alltheseas** [jinglescode/nostr-url-shortener#4]
_what happens_
When I paste a very long string in the URL box, it does not fit in the box.

<img width="763" alt="Screenshot 2023-08-15 at 4 34 20 PM" src="https://github.com/jinglescode/nostr-url-shortener/assets/64376233/8b614bf7-96ae-478c-ae98-953378604f81">

_what I would like to happen_
I would like to see the whole string without interference

**Comment by jinglescode** [comment]
strange, the text shouldnt cover the `enter` button anymore. 
but nevertheless, yea, could tranform it to dyanmic height text field to show full text.
